name: Bao component base workflow

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  gitlint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - if: ${{ github.event_name == 'pull_request' }}
        run: >
            git config --global --add safe.directory $(realpath .) &&
            make gitlint GITLINT_BASE=${{ github.event.pull_request.base.sha }} && echo 3
      - if: ${{ github.event_name == 'push' }}
        run: >
            git config --global --add safe.directory $(realpath .) &&
            make gitlint GITLINT_BASE=${{ github.event.before }} && echo 2
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: >
            git config --global --add safe.directory $(realpath .) &&
            make gitlint GITLINT_BASE=HEAD && echo 1
